Repository grafana/clickhouse-datasource, pull requests merged in 2023-08, with the labels that each got.

#470 Allow for converting data returned from `SimpleAggregateFunction`
  pkg/converters/converters.go
  pkg/converters/converters_test.go
  pkg/plugin/driver.go
  pkg/plugin/driver_test.go
Labels: type/bug, go, effort/medium

#486 Add a converter for the `Point` geo type
  cspell.config.json
  pkg/converters/converters.go
  pkg/converters/converters_test.go
Labels: datasource/ClickHouse, area/backend, go, effort/small

#489 Use date.UnixMilli in newTimeFilter func
  pkg/macros/macros.go
  pkg/macros/macros_test.go
Labels: datasource/ClickHouse, area/backend, go, effort/small

#494 Bump grafana-plugin-sdk-go, testcontainers-go, clickhouse-go
  go.mod
  go.sum
Labels: type/bug, area/backend, dependencies

#492 Pin e2e selectors package
  e2e/e2ek6.test.js
Labels: datasource/ClickHouse

#496 Add Docker image builds and post `docker pull` commands for local testing
  .github/workflows/pull-request-image.yml
Labels: datasource/ClickHouse, github_actions, effort/medium

#502 Remove cypress testing
  .gitignore
  cspell.config.json
  cypress-e2e/integration/smoke.spec.ts
  cypress-e2e/screenshots/expected/smoke.spec.ts/panel-visualization.png
  cypress-e2e/tsconfig.json
  package.json
  yarn.lock
Labels: datasource/ClickHouse
