Repository grafana/clickhouse-datasource, pull requests merged in 2023-07, with the labels that each got.

#399 Add k6 testing
  cspell.config.json
  e2e/e2ek6.test.js
Labels: enhancement, datasource/ClickHouse, effort/medium

#457 Bump Go version used in CI to 1.20
  .github/workflows/run-backend-tests.yml
  .github/workflows/run-frontend-tests.yml
Labels: type/bug, area/backend, effort/small

#456 Parse queryTimeout when either string or number
  pkg/plugin/driver_test.go
  pkg/plugin/settings.go
Labels: effort/small

#459 Fix conditionAll handling
  src/data/CHDatasource.test.ts
  src/data/CHDatasource.ts
Labels: effort/small

#460 Ensure databases, tables, and columns are escaped correctly
  src/components/queryBuilder/utils.spec.ts
  src/components/queryBuilder/utils.ts
  src/data/CHDatasource.test.ts
  src/data/CHDatasource.ts
Labels: effort/small

#469 Fix auto formatting by reverting to table correctly
  src/components/editor.ts
  src/data/ast.test.ts
  src/data/ast.ts
  src/views/CHQueryEditor.tsx
Labels: changelog
