Repository grafana/clickhouse-datasource, pull requests merged in 2023-11, with the labels that each got.

#580 Add merge method
  .github/workflows/dependabot-reviewer.yml
Labels: effort/none

#587 Bump grafana-plugin-sdk-go to 0.193.0 and Go to 1.21
  .github/workflows/pull-request-image.yml
  .github/workflows/run-backend-tests.yml
  .github/workflows/run-frontend-tests.yml
  .github/workflows/run-k6e2e-tests.yml
  go.mod
  go.sum
  pkg/plugin/driver.go
  pkg/plugin/settings.go
Labels: datasource/ClickHouse

#597 Remove unused ComplexTypes map
  pkg/converters/converters.go
Labels: datasource/ClickHouse, area/backend
