Repository grafana/clickhouse-datasource, pull requests merged in 2024-07, with the labels that each got.

#890 Update trace queries to better handle time fields
  src/data/sqlGenerator.test.ts
  src/data/sqlGenerator.ts
Labels: effort/small

#898 Release v4.3.0
  CHANGELOG.md
  package.json
Labels: datasource/ClickHouse, area/backend, effort/small

#919 Fix OTel dashboard
  src/dashboards/opentelemetry-clickhouse.json
Labels: type/bug, effort/small
